### ISSUE TITLE
Bigger preview

### ISSUE THREAD

**Issue by Sheraff** [bevesce/unicode-symbols-search#4]
Cool workflow, I've been looking for something like that! Do you think you could make the preview bigger by putting it as the icon (you'd have to dynamically generate these though) instead of as the title?

**Comment by bevesce** [comment]
I'm afraid that generating images dynamically would make workflow very sluggish (of course I'm not sure, it should be tested) and dependent of some external library, on the other hand including over 15k images in the workflow would make it very large. So, I'm not sure if it is feasible and at the moment I'm not inclined to test it out. Maybe when I have more free time I'll check it out.

**Comment by jacobsvante** [comment]
Seems reasonably fast to me:

``` shell
$ time gm convert -pointsize 256 -font /System/Library/Fonts/Helvetica.dfont \
-size 512x512 -antialias -background transparent -trim +repage caption:"∑" \
-thumbnail '256x256>' -gravity center -extent 256x256 png:- > /dev/null
```

Gives the following on my 2015 MBP dual-core 2.9GHz:

```
gm convert -pointsize 256 -font /System/Library/Fonts/Helvetica.dfont -size
0.02s user 0.01s system 83% cpu 0.035 total
```

**Comment by bevesce** [comment]
There are over 15k symbols in the workflow, and there is no way in Alfred's API to render only those needed on screen. But I checked and it turns out speed is not an issue. 15k images in size suitable for Alfred won't take as mush space as I expected so they could be included in workflow folder.

That said, using this one gm command is not enough, many symbols don't render properly this way, and lots and lots of them don't have glyph in Helvetica. Sorting this out would take more time than I'm willing to invest in this project right now, but any PRs are welcome.
